apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: merlin-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  defaultBackend:
    service:
      name: merlin-ui
      port:
        number: 80
  tls:
    - hosts:
        - themerlin.app
      secretName: merlin-tls
  rules:
    - host: "themerlin.app"
      http:
        paths:
          - pathType: Prefix
            path: "/api"
            backend:
              service:
                name: merlin-api
                port:
                  number: 80