name: Build & Test PR

on:
  pull_request:
    branches:
      - main

jobs:
  build_api:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout master
        uses: actions/checkout@main

      - name: Build container image
        run: docker build -t ${{ secrets.REGISTRY_NAME }}/merlin-api:$(echo $GITHUB_SHA | head -c7) -f .docker/Dockerfile.api .

  build_ui:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout master
        uses: actions/checkout@main

      - name: Build container image
        run: docker build -t ${{ secrets.REGISTRY_NAME }}/merlin-ui:$(echo $GITHUB_SHA | head -c7) -f .docker/Dockerfile.ui .